project_name: dkg
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    main: main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.build={{.Env.VERSION}}
      - -X main.version={{.Env.VERSION}}
      - -X 'github.com/arcana-network/dkgnode/versioning.Version={{.Env.VERSION}}'
      - -X 'github.com/arcana-network/dkgnode/config.DefaultGatewayURL={{.Env.GATEWAY_URL}}'
      - -X 'github.com/arcana-network/dkgnode/config.DefaultContractAddress={{.Env.CONTRACT_ADDRESS}}'
      - -X 'github.com/arcana-network/dkgnode/config.DefaultBlockchainRPCURL={{.Env.BLOCKCHAIN_RPC_URL}}'
      - -X 'github.com/arcana-network/dkgnode/config.DefaultPasswordlessUrl={{.Env.PASSWORDLESS_URL}}'
      - -X 'github.com/arcana-network/dkgnode/config.DefaultOAuthUrl={{.Env.OAUTH_URL}}'

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version}}-checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
