version: "3"

services:
  one:
    build: .
    ports:
      - "1080"
      - "8080:8080"
    volumes:
      - ./assets/config.local.1.json:/config.json
    networks:
      arcana:
        ipv4_address: 192.167.10.11
  two:
    build: .
    ports:
      - "1080"
      - "8081:8081"
    volumes:
      - ./assets/config.local.2.json:/config.json
    networks:
      arcana:
        ipv4_address: 192.167.10.12
  three:
    build: .
    ports:
      - "1080"
      - "8082:8082"
    volumes:
      - ./assets/config.local.3.json:/config.json
    networks:
      arcana:
        ipv4_address: 192.167.10.13
  four:
    build: .
    ports:
      - "1080"
      - "8083:8083"
    volumes:
      - ./assets/config.local.4.json:/config.json
    networks:
      arcana:
        ipv4_address: 192.167.10.14
  five:
    build: .
    ports:
      - "1080"
      - "8084:8084"
    volumes:
      - ./assets/config.local.5.json:/config.json
    networks:
      arcana:
        ipv4_address: 192.167.10.15
  six:
    build: .
    ports:
      - "1080"
      - "8085:8085"
    volumes:
      - ./assets/config.local.6.json:/config.json
    networks:
      arcana:
        ipv4_address: 192.167.10.16
networks:
  arcana:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/24
